<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Errors;

class ClerkErrors71Throwable extends \RuntimeException
{
    public ClerkErrors71 $container;

    public function __construct(string $message, int $statusCode, ClerkErrors71 $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}