<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


enum CodeType: string
{
    case Totp = 'totp';
    case BackupCode = 'backup_code';
}
