<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** CreateOrganizationInvitationPrivateMetadata - Metadata saved on the organization invitation, fully accessible (read/write) from the Backend API but not visible from the Frontend API. */
class CreateOrganizationInvitationPrivateMetadata
{

    public function __construct()
    {
    }
}