<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class CreateOrganizationRequestBody
{
    /**
     * The name of the new organization
     *
     * @var string $name
     */
    #[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;

    /**
     * The ID of the User who will become the administrator for the new organization
     *
     * @var string $createdBy
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_by')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $createdBy;

    /**
     * Metadata saved on the organization, accessible only from the Backend API
     *
     * @var ?\Clerk\Backend\Models\Operations\CreateOrganizationPrivateMetadata $privateMetadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('private_metadata')]
    #[\JMS\Serializer\Annotation\Type('Clerk\Backend\Models\Operations\CreateOrganizationPrivateMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateOrganizationPrivateMetadata $privateMetadata = null;

    /**
     * Metadata saved on the organization, read-only from the Frontend API and fully accessible (read/write) from the Backend API
     *
     * @var ?\Clerk\Backend\Models\Operations\CreateOrganizationPublicMetadata $publicMetadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('public_metadata')]
    #[\JMS\Serializer\Annotation\Type('Clerk\Backend\Models\Operations\CreateOrganizationPublicMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateOrganizationPublicMetadata $publicMetadata = null;

    /**
     * A slug for the new organization.
     *
     * Can contain only lowercase alphanumeric characters and the dash "-".
     * Must be unique for the instance.
     *
     * @var ?string $slug
     */
    #[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $slug = null;

    /**
     * The maximum number of memberships allowed for this organization
     *
     * @var ?int $maxAllowedMemberships
     */
    #[\JMS\Serializer\Annotation\SerializedName('max_allowed_memberships')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $maxAllowedMemberships = null;

    public function __construct()
    {
        $this->name = '';
        $this->createdBy = '';
        $this->privateMetadata = null;
        $this->publicMetadata = null;
        $this->slug = null;
        $this->maxAllowedMemberships = null;
    }
}