<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class CreateUserTOTPRequest
{
    /**
     * The ID of the user for whom the TOTP is being created.
     *
     * @var string $userId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=user_id')]
    public string $userId;

    /**
     * @param  string  $userId
     */
    public function __construct(string $userId)
    {
        $this->userId = $userId;
    }
}