<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** CreateSessionTokenFromTemplateResponseBody - OK */
class CreateSessionTokenFromTemplateResponseBody
{
    /**
     *
     * @var ?ObjectT $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\ObjectT|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ObjectT $object = null;

    /**
     *
     * @var ?string $jwt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('jwt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jwt = null;

    /**
     * @param  ?ObjectT  $object
     * @param  ?string  $jwt
     */
    public function __construct(?ObjectT $object = null, ?string $jwt = null)
    {
        $this->object = $object;
        $this->jwt = $jwt;
    }
}