<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class CreateOrganizationMembershipRequest
{
    /**
     * The ID of the organization where the new membership will be created
     *
     * @var string $organizationId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organization_id')]
    public string $organizationId;

    /**
     *
     * @var CreateOrganizationMembershipRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public CreateOrganizationMembershipRequestBody $requestBody;

    /**
     * @param  string  $organizationId
     * @param  CreateOrganizationMembershipRequestBody  $requestBody
     */
    public function __construct(string $organizationId, CreateOrganizationMembershipRequestBody $requestBody)
    {
        $this->organizationId = $organizationId;
        $this->requestBody = $requestBody;
    }
}