<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** CreateOrganizationPrivateMetadata - Metadata saved on the organization, accessible only from the Backend API */
class CreateOrganizationPrivateMetadata
{
    public function __construct() {}
}