<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class CreateEmailAddressRequestBody
{
    /**
     * The ID representing the user
     *
     * @var ?string $userId
     */
    #[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $userId = null;

    /**
     * The new email address. Must adhere to the RFC 5322 specification for email address format.
     *
     * @var ?string $emailAddress
     */
    #[\JMS\Serializer\Annotation\SerializedName('email_address')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $emailAddress = null;

    /**
     * When created, the email address will be marked as verified.
     *
     * @var ?bool $verified
     */
    #[\JMS\Serializer\Annotation\SerializedName('verified')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $verified = null;

    /**
     * Create this email address as the primary email address for the user.
     *
     * Default: false, unless it is the first email address.
     *
     * @var ?bool $primary
     */
    #[\JMS\Serializer\Annotation\SerializedName('primary')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $primary = null;

    public function __construct()
    {
        $this->userId = null;
        $this->emailAddress = null;
        $this->verified = null;
        $this->primary = null;
    }
}