<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** CreateSessionTokenFromTemplateResponseBody - OK */
class CreateSessionTokenFromTemplateResponseBody
{
    #[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Clerk\Backend\Models\Operations\ObjectT>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ObjectT $object = null;

    #[\JMS\Serializer\Annotation\SerializedName('jwt')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $jwt = null;

    public function __construct()
    {
        $this->object = null;
        $this->jwt = null;
    }
}