<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class CreateBlocklistIdentifierRequestBody
{
    /**
     * The identifier to be added in the block-list.
     *
     * This can be an email address, a phone number or a web3 wallet.
     *
     * @var string $identifier
     */
    #[\JMS\Serializer\Annotation\SerializedName('identifier')]
    public string $identifier;

    /**
     * @param  ?string  $identifier
     */
    public function __construct(?string $identifier = null)
    {
        $this->identifier = $identifier;
    }
}