<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class DeleteDomainRequest
{
    /**
     * The ID of the domain that will be deleted. Must be a satellite domain.
     *
     * @var string $domainId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=domain_id')]
    public string $domainId;

    /**
     * @param  string  $domainId
     */
    public function __construct(string $domainId)
    {
        $this->domainId = $domainId;
    }
}