<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class DeleteOAuthApplicationRequest
{
    /**
     * The ID of the OAuth application to delete
     *
     * @var string $oauthApplicationId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=oauth_application_id')]
    public string $oauthApplicationId;

    public function __construct()
    {
        $this->oauthApplicationId = '';
    }
}