<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class GetOAuthAccessTokenRequest
{
    /**
     * The ID of the user for which to retrieve the OAuth access token
     *
     * @var string $userId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=user_id')]
    public string $userId;

    /**
     * The ID of the OAuth provider (e.g. `oauth_google`)
     *
     * @var string $provider
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=provider')]
    public string $provider;

    public function __construct()
    {
        $this->userId = '';
        $this->provider = '';
    }
}