<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class GetPhoneNumberRequest
{
    /**
     * The ID of the phone number to retrieve
     *
     * @var string $phoneNumberId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=phone_number_id')]
    public string $phoneNumberId;

    /**
     * @param  string  $phoneNumberId
     */
    public function __construct(string $phoneNumberId)
    {
        $this->phoneNumberId = $phoneNumberId;
    }
}