<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class GetTemplateListRequest
{
    /**
     * The type of templates to list (email or SMS)
     *
     * @var \Clerk\Backend\Models\Operations\TemplateType $templateType
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=template_type')]
    public TemplateType $templateType;

    public function __construct()
    {
        $this->templateType = \Clerk\Backend\Models\Operations\TemplateType::Email;
    }
}