<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class GetUsersCountRequest
{
    /**
     * Counts users with the specified email addresses.
     *
     * Accepts up to 100 email addresses.
     * Any email addresses not found are ignored.
     *
     * @var ?array<string> $emailAddress
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=email_address')]
    public ?array $emailAddress = null;

    /**
     * Counts users with the specified phone numbers.
     *
     * Accepts up to 100 phone numbers.
     * Any phone numbers not found are ignored.
     *
     * @var ?array<string> $phoneNumber
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=phone_number')]
    public ?array $phoneNumber = null;

    /**
     * Counts users with the specified external ids.
     *
     * Accepts up to 100 external ids.
     * Any external ids not found are ignored.
     *
     * @var ?array<string> $externalId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=external_id')]
    public ?array $externalId = null;

    /**
     * Counts users with the specified usernames.
     *
     * Accepts up to 100 usernames.
     * Any usernames not found are ignored.
     *
     * @var ?array<string> $username
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=username')]
    public ?array $username = null;

    /**
     * Counts users with the specified web3 wallet addresses.
     *
     * Accepts up to 100 web3 wallet addresses.
     * Any web3 wallet addressed not found are ignored.
     *
     * @var ?array<string> $web3Wallet
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=web3_wallet')]
    public ?array $web3Wallet = null;

    /**
     * Counts users with the user ids specified.
     *
     * Accepts up to 100 user ids.
     * Any user ids not found are ignored.
     *
     * @var ?array<string> $userId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user_id')]
    public ?array $userId = null;

    /**
     * Counts users that match the given query.
     *
     * For possible matches, we check the email addresses, phone numbers, usernames, web3 wallets, user ids, first and last names.
     * The query value doesn't need to match the exact value you are looking for, it is capable of partial matches as well.
     *
     * @var ?string $query
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=query')]
    public ?string $query = null;

    /**
     * @param  ?array<string>  $emailAddress
     * @param  ?array<string>  $phoneNumber
     * @param  ?array<string>  $externalId
     * @param  ?array<string>  $username
     * @param  ?array<string>  $web3Wallet
     * @param  ?array<string>  $userId
     * @param  ?string  $query
     */
    public function __construct(?array $emailAddress = null, ?array $phoneNumber = null, ?array $externalId = null, ?array $username = null, ?array $web3Wallet = null, ?array $userId = null, ?string $query = null)
    {
        $this->emailAddress = $emailAddress;
        $this->phoneNumber = $phoneNumber;
        $this->externalId = $externalId;
        $this->username = $username;
        $this->web3Wallet = $web3Wallet;
        $this->userId = $userId;
        $this->query = $query;
    }
}