<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class ListOrganizationInvitationsRequest
{
    /**
     * The organization ID.
     *
     * @var string $organizationId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organization_id')]
    public string $organizationId;

    /**
     * Applies a limit to the number of results returned.
     *
     * Can be used for paginating the results together with `offset`.
     *
     * @var ?float $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?float $limit = null;

    /**
     * Skip the first `offset` results when paginating.
     *
     * Needs to be an integer greater or equal to zero.
     * To be used in conjunction with `limit`.
     *
     * @var ?float $offset
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?float $offset = null;

    /**
     * Filter organization invitations based on their status
     *
     * @var ?ListOrganizationInvitationsQueryParamStatus $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?ListOrganizationInvitationsQueryParamStatus $status = null;

    /**
     * @param  ?string  $organizationId
     * @param  ?float  $limit
     * @param  ?float  $offset
     * @param  ?ListOrganizationInvitationsQueryParamStatus  $status
     */
    public function __construct(?string $organizationId = null, ?float $limit = null, ?float $offset = null, ?ListOrganizationInvitationsQueryParamStatus $status = null)
    {
        $this->organizationId = $organizationId;
        $this->limit = $limit;
        $this->offset = $offset;
        $this->status = $status;
    }
}