<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class MergeOrganizationMetadataRequestBody
{
    /**
     * Metadata saved on the organization, that is visible to both your frontend and backend.
     *
     * The new object will be merged with the existing value.
     *
     * @var ?MergeOrganizationMetadataPublicMetadata $publicMetadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('public_metadata')]
    #[\JMS\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\MergeOrganizationMetadataPublicMetadata|null')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?MergeOrganizationMetadataPublicMetadata $publicMetadata = null;

    /**
     * Metadata saved on the organization that is only visible to your backend.
     *
     * The new object will be merged with the existing value.
     *
     * @var ?MergeOrganizationMetadataPrivateMetadata $privateMetadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('private_metadata')]
    #[\JMS\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\MergeOrganizationMetadataPrivateMetadata|null')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?MergeOrganizationMetadataPrivateMetadata $privateMetadata = null;

    /**
     * @param  ?MergeOrganizationMetadataPublicMetadata  $publicMetadata
     * @param  ?MergeOrganizationMetadataPrivateMetadata  $privateMetadata
     */
    public function __construct(?MergeOrganizationMetadataPublicMetadata $publicMetadata = null, ?MergeOrganizationMetadataPrivateMetadata $privateMetadata = null)
    {
        $this->publicMetadata = $publicMetadata;
        $this->privateMetadata = $privateMetadata;
    }
}