<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/**
 * MergeOrganizationMetadataPublicMetadata - Metadata saved on the organization, that is visible to both your frontend and backend.
 *
 * The new object will be merged with the existing value.
 */
class MergeOrganizationMetadataPublicMetadata
{
    public function __construct()
    {
    }
}