<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class PreviewTemplateRequest
{
    /**
     * The type of template to preview
     *
     * @var string $templateType
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=template_type')]
    public string $templateType;

    /**
     * The slug of the template to preview
     *
     * @var string $slug
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=slug')]
    public string $slug;

    /**
     * Required parameters
     *
     * @var ?PreviewTemplateRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?PreviewTemplateRequestBody $requestBody = null;

    /**
     * @param  ?string  $templateType
     * @param  ?string  $slug
     * @param  ?PreviewTemplateRequestBody  $requestBody
     */
    public function __construct(?string $templateType = null, ?string $slug = null, ?PreviewTemplateRequestBody $requestBody = null)
    {
        $this->templateType = $templateType;
        $this->slug = $slug;
        $this->requestBody = $requestBody;
    }
}