<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** PrivateMetadata - Metadata saved on the user, that is only visible to your Backend API */
class PrivateMetadata
{
    public function __construct() {}
}