<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class ResponseBody
{
    /**
     *
     * @var ?string $object
     */
    #[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $object = null;

    /**
     * External account ID
     *
     * @var ?string $externalAccountId
     */
    #[\JMS\Serializer\Annotation\SerializedName('external_account_id')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $externalAccountId = null;

    /**
     * The unique ID of the user in the external provider's system
     *
     * @var ?string $providerUserId
     */
    #[\JMS\Serializer\Annotation\SerializedName('provider_user_id')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $providerUserId = null;

    /**
     * The access token
     *
     * @var ?string $token
     */
    #[\JMS\Serializer\Annotation\SerializedName('token')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $token = null;

    /**
     * The ID of the provider
     *
     * @var ?string $provider
     */
    #[\JMS\Serializer\Annotation\SerializedName('provider')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $provider = null;

    /**
     *
     * @var ?GetOAuthAccessTokenPublicMetadata $publicMetadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('public_metadata')]
    #[\JMS\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\GetOAuthAccessTokenPublicMetadata|null')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GetOAuthAccessTokenPublicMetadata $publicMetadata = null;

    /**
     *
     * @var ?string $label
     */
    #[\JMS\Serializer\Annotation\SerializedName('label')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $label = null;

    /**
     * The list of scopes that the token is valid for.
     *
     * Only present for OAuth 2.0 tokens.
     *
     * @var ?array<string> $scopes
     */
    #[\JMS\Serializer\Annotation\SerializedName('scopes')]
    #[\JMS\Serializer\Annotation\Type('array<string>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $scopes = null;

    /**
     * The token secret. Only present for OAuth 1.0 tokens.
     *
     * @var ?string $tokenSecret
     */
    #[\JMS\Serializer\Annotation\SerializedName('token_secret')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tokenSecret = null;

    /**
     * @param  ?string  $object
     * @param  ?string  $externalAccountId
     * @param  ?string  $providerUserId
     * @param  ?string  $token
     * @param  ?string  $provider
     * @param  ?GetOAuthAccessTokenPublicMetadata  $publicMetadata
     * @param  ?string  $label
     * @param  ?array<string>  $scopes
     * @param  ?string  $tokenSecret
     */
    public function __construct(?string $object = null, ?string $externalAccountId = null, ?string $providerUserId = null, ?string $token = null, ?string $provider = null, ?GetOAuthAccessTokenPublicMetadata $publicMetadata = null, ?string $label = null, ?array $scopes = null, ?string $tokenSecret = null)
    {
        $this->object = $object;
        $this->externalAccountId = $externalAccountId;
        $this->providerUserId = $providerUserId;
        $this->token = $token;
        $this->provider = $provider;
        $this->publicMetadata = $publicMetadata;
        $this->label = $label;
        $this->scopes = $scopes;
        $this->tokenSecret = $tokenSecret;
    }
}