<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class RevertTemplateRequest
{
    /**
     * The type of template to revert
     *
     * @var RevertTemplatePathParamTemplateType $templateType
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=template_type')]
    public RevertTemplatePathParamTemplateType $templateType;

    /**
     * The slug of the template to revert
     *
     * @var string $slug
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=slug')]
    public string $slug;

    /**
     * @param  RevertTemplatePathParamTemplateType  $templateType
     * @param  string  $slug
     */
    public function __construct(RevertTemplatePathParamTemplateType $templateType, string $slug)
    {
        $this->templateType = $templateType;
        $this->slug = $slug;
    }
}