<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class RevokeActorTokenRequest
{
    /**
     * The ID of the actor token to be revoked.
     *
     * @var string $actorTokenId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=actor_token_id')]
    public string $actorTokenId;

    /**
     * @param  string  $actorTokenId
     */
    public function __construct(string $actorTokenId)
    {
        $this->actorTokenId = $actorTokenId;
    }
}