<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** The type of templates to list (email or SMS) */
enum TemplateType: string
{
    case Email = 'email';
    case Sms = 'sms';
}
