<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class ToggleTemplateDeliveryRequest
{
    /**
     * The type of template to toggle delivery for
     *
     * @var \Clerk\Backend\Models\Operations\ToggleTemplateDeliveryPathParamTemplateType $templateType
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=template_type')]
    public ToggleTemplateDeliveryPathParamTemplateType $templateType;

    /**
     * The slug of the template for which to toggle delivery
     *
     * @var string $slug
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=slug')]
    public string $slug;

    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?ToggleTemplateDeliveryRequestBody $requestBody = null;

    public function __construct()
    {
        $this->templateType = \Clerk\Backend\Models\Operations\ToggleTemplateDeliveryPathParamTemplateType::Email;
        $this->slug = '';
        $this->requestBody = null;
    }
}