<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class UpdateEmailAddressRequest
{
    /**
     * The ID of the email address to update
     *
     * @var string $emailAddressId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=email_address_id')]
    public string $emailAddressId;

    /**
     *
     * @var ?UpdateEmailAddressRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?UpdateEmailAddressRequestBody $requestBody = null;

    /**
     * @param  string  $emailAddressId
     * @param  ?UpdateEmailAddressRequestBody  $requestBody
     */
    public function __construct(string $emailAddressId, ?UpdateEmailAddressRequestBody $requestBody = null)
    {
        $this->emailAddressId = $emailAddressId;
        $this->requestBody = $requestBody;
    }
}