<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class UpdateOrganizationMembershipRequestBody
{
    /**
     * The new role of the given membership.
     *
     * @var string $role
     */
    #[\JMS\Serializer\Annotation\SerializedName('role')]
    public string $role;

    /**
     * @param  ?string  $role
     */
    public function __construct(?string $role = null)
    {
        $this->role = $role;
    }
}