<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class UpdateSignUpRequestBody
{
    /**
     * Specifies whether a custom action has run for this sign-up attempt.
     *
     * This is important when your instance has been configured to require a custom action to run before converting a sign-up into a user.
     * After executing any external business logic you deem necessary, you can mark the sign-up as ready-to-convert by setting `custom_action` to `true`.
     *
     * @var ?bool $customAction
     */
    #[\JMS\Serializer\Annotation\SerializedName('custom_action')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $customAction = null;

    /**
     * The ID of the guest attempting to sign up as used in your external systems or your previous authentication solution.
     *
     * This will be copied to the resulting user when the sign-up is completed.
     *
     * @var ?string $externalId
     */
    #[\JMS\Serializer\Annotation\SerializedName('external_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $externalId = null;

    public function __construct()
    {
        $this->customAction = null;
        $this->externalId = null;
    }
}