<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class UpdateOAuthApplicationRequestBody
{
    /**
     * The new name of the OAuth application
     *
     * @var ?string $name
     */
    #[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;

    /**
     * The new callback URL of the OAuth application
     *
     * @var ?string $callbackUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('callback_url')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $callbackUrl = null;

    /**
     * Define the allowed scopes for the new OAuth applications that dictate the user payload of the OAuth user info endpoint. Available scopes are `profile`, `email`, `public_metadata`, `private_metadata`. Provide the requested scopes as a string, separated by spaces.
     *
     * @var ?string $scopes
     */
    #[\JMS\Serializer\Annotation\SerializedName('scopes')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $scopes = null;

    /**
     * @param  ?string  $name
     * @param  ?string  $callbackUrl
     * @param  ?string  $scopes
     */
    public function __construct(?string $name = null, ?string $callbackUrl = null, ?string $scopes = null)
    {
        $this->name = $name;
        $this->callbackUrl = $callbackUrl;
        $this->scopes = $scopes;
    }
}