<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class UpdateOrganizationMembershipMetadataRequestBody
{
    /**
     * Metadata saved on the organization membership, that is visible to both your frontend and backend.
     *
     * The new object will be merged with the existing value.
     *
     * @var ?\Clerk\Backend\Models\Operations\UpdateOrganizationMembershipMetadataPublicMetadata $publicMetadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('public_metadata')]
    #[\JMS\Serializer\Annotation\Type('Clerk\Backend\Models\Operations\UpdateOrganizationMembershipMetadataPublicMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UpdateOrganizationMembershipMetadataPublicMetadata $publicMetadata = null;

    /**
     * Metadata saved on the organization membership that is only visible to your backend.
     *
     * The new object will be merged with the existing value.
     *
     * @var ?\Clerk\Backend\Models\Operations\UpdateOrganizationMembershipMetadataPrivateMetadata $privateMetadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('private_metadata')]
    #[\JMS\Serializer\Annotation\Type('Clerk\Backend\Models\Operations\UpdateOrganizationMembershipMetadataPrivateMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UpdateOrganizationMembershipMetadataPrivateMetadata $privateMetadata = null;

    public function __construct()
    {
        $this->publicMetadata = null;
        $this->privateMetadata = null;
    }
}