<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** UpdateSAMLConnectionAttributeMapping - Define the atrtibute name mapping between Identity Provider and Clerk's user properties */
class UpdateSAMLConnectionAttributeMapping
{
    /**
     *
     * @var ?string $userId
     */
    #[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $userId = null;

    /**
     *
     * @var ?string $emailAddress
     */
    #[\JMS\Serializer\Annotation\SerializedName('email_address')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $emailAddress = null;

    /**
     *
     * @var ?string $firstName
     */
    #[\JMS\Serializer\Annotation\SerializedName('first_name')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\JMS\Serializer\Annotation\SerializedName('last_name')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lastName = null;

    /**
     * @param  ?string  $userId
     * @param  ?string  $emailAddress
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     */
    public function __construct(?string $userId = null, ?string $emailAddress = null, ?string $firstName = null, ?string $lastName = null)
    {
        $this->userId = $userId;
        $this->emailAddress = $emailAddress;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
    }
}