<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class UpdateUserMetadataRequest
{
    /**
     * The ID of the user whose metadata will be updated and merged
     *
     * @var string $userId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=user_id')]
    public string $userId;

    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?UpdateUserMetadataRequestBody $requestBody = null;

    public function __construct()
    {
        $this->userId = '';
        $this->requestBody = null;
    }
}