<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class UpdateSAMLConnectionRequest
{
    /**
     * The ID of the SAML Connection to update
     *
     * @var string $samlConnectionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=saml_connection_id')]
    public string $samlConnectionId;

    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public UpdateSAMLConnectionRequestBody $requestBody;

    public function __construct()
    {
        $this->samlConnectionId = '';
        $this->requestBody = new \Clerk\Backend\Models\Operations\UpdateSAMLConnectionRequestBody();
    }
}