<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class UploadOrganizationLogoRequestBody
{
    /**
     * The ID of the user that will be credited with the image upload.
     *
     * @var string $uploaderUserId
     */
    #[SpeakeasyMetadata('multipartForm:name=uploader_user_id')]
    public string $uploaderUserId;

    /**
     *
     * @var UploadOrganizationLogoFile $file
     */
    #[SpeakeasyMetadata('multipartForm:file=true')]
    public UploadOrganizationLogoFile $file;

    /**
     * @param  string  $uploaderUserId
     * @param  UploadOrganizationLogoFile  $file
     */
    public function __construct(string $uploaderUserId, UploadOrganizationLogoFile $file)
    {
        $this->uploaderUserId = $uploaderUserId;
        $this->file = $file;
    }
}