<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class UploadOrganizationLogoFile
{
    #[SpeakeasyMetadata('multipartForm:name=file')]
    public string $fileName;

    #[SpeakeasyMetadata('multipartForm:content=true')]
    public string $content;

    public function __construct()
    {
        $this->fileName = '';
        $this->content = '';
    }
}