<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class UpsertTemplateRequest
{
    /**
     * The type of template to update
     *
     * @var UpsertTemplatePathParamTemplateType $templateType
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=template_type')]
    public UpsertTemplatePathParamTemplateType $templateType;

    /**
     * The slug of the template to update
     *
     * @var string $slug
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=slug')]
    public string $slug;

    /**
     *
     * @var ?UpsertTemplateRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?UpsertTemplateRequestBody $requestBody = null;

    /**
     * @param  ?UpsertTemplatePathParamTemplateType  $templateType
     * @param  ?string  $slug
     * @param  ?UpsertTemplateRequestBody  $requestBody
     */
    public function __construct(?UpsertTemplatePathParamTemplateType $templateType = null, ?string $slug = null, ?UpsertTemplateRequestBody $requestBody = null)
    {
        $this->templateType = $templateType;
        $this->slug = $slug;
        $this->requestBody = $requestBody;
    }
}