<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class UserWeb3WalletDeleteRequest
{
    /**
     * The ID of the user that owns the web3 wallet
     *
     * @var string $userId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=user_id')]
    public string $userId;

    /**
     * The ID of the web3 wallet identity to be deleted
     *
     * @var string $web3WalletIdentificationId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=web3_wallet_identification_id')]
    public string $web3WalletIdentificationId;

    /**
     * @param  string  $userId
     * @param  string  $web3WalletIdentificationId
     */
    public function __construct(string $userId, string $web3WalletIdentificationId)
    {
        $this->userId = $userId;
        $this->web3WalletIdentificationId = $web3WalletIdentificationId;
    }
}