<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class VerifySessionRequest
{
    /**
     * The ID of the session
     *
     * @var string $sessionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=session_id')]
    public string $sessionId;

    /**
     * Parameters.
     *
     * @var ?\Clerk\Backend\Models\Operations\VerifySessionRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?VerifySessionRequestBody $requestBody = null;

    public function __construct()
    {
        $this->sessionId = '';
        $this->requestBody = null;
    }
}