<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** VerifySessionRequestBody - Parameters. */
class VerifySessionRequestBody
{
    /**
     * The JWT that is sent via the `__session` cookie from your frontend.
     *
     * Note: this JWT must be associated with the supplied session ID.
     *
     * @var ?string $token
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('token')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $token = null;

    /**
     * @param  ?string  $token
     */
    public function __construct(?string $token = null)
    {
        $this->token = $token;
    }
}