<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** ActorToken - Success */
class ActorToken
{
    /**
     *
     * @var ActorTokenObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ActorTokenObject')]
    public ActorTokenObject $object;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var ActorTokenStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ActorTokenStatus')]
    public ActorTokenStatus $status;

    /**
     *
     * @var string $userId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('user_id')]
    public string $userId;

    /**
     *
     * @var ActorTokenActor $actor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('actor')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ActorTokenActor')]
    public ActorTokenActor $actor;

    /**
     * Unix timestamp of creation.
     *
     *
     *
     * @var int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Unix timestamp of last update.
     *
     *
     *
     * @var int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     *
     * @var ?string $token
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('token')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $token = null;

    /**
     *
     * @var ?string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     * @param  ActorTokenObject  $object
     * @param  string  $id
     * @param  ActorTokenStatus  $status
     * @param  string  $userId
     * @param  ActorTokenActor  $actor
     * @param  int  $createdAt
     * @param  int  $updatedAt
     * @param  ?string  $token
     * @param  ?string  $url
     */
    public function __construct(ActorTokenObject $object, string $id, ActorTokenStatus $status, string $userId, ActorTokenActor $actor, int $createdAt, int $updatedAt, ?string $token = null, ?string $url = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->status = $status;
        $this->userId = $userId;
        $this->actor = $actor;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->token = $token;
        $this->url = $url;
    }
}