<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** AllowlistIdentifier - Success */
class AllowlistIdentifier
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     *
     *
     * @var ?AllowlistIdentifierObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\AllowlistIdentifierObject|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AllowlistIdentifierObject $object = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?string $invitationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invitation_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invitationId = null;

    /**
     * An email address or a phone number.
     *
     *
     *
     * @var ?string $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     *
     * @var ?IdentifierType $identifierType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\IdentifierType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?IdentifierType $identifierType = null;

    /**
     *
     * @var ?string $instanceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('instance_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $instanceId = null;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var ?int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $createdAt = null;

    /**
     * Unix timestamp of last update.
     *
     *
     *
     * @var ?int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $updatedAt = null;

    /**
     * @param  ?AllowlistIdentifierObject  $object
     * @param  ?string  $id
     * @param  ?string  $invitationId
     * @param  ?string  $identifier
     * @param  ?IdentifierType  $identifierType
     * @param  ?string  $instanceId
     * @param  ?int  $createdAt
     * @param  ?int  $updatedAt
     */
    public function __construct(?AllowlistIdentifierObject $object = null, ?string $id = null, ?string $invitationId = null, ?string $identifier = null, ?IdentifierType $identifierType = null, ?string $instanceId = null, ?int $createdAt = null, ?int $updatedAt = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->invitationId = $invitationId;
        $this->identifier = $identifier;
        $this->identifierType = $identifierType;
        $this->instanceId = $instanceId;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }
}