<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Client
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     *
     *
     * @var \Clerk\Backend\Models\Components\ObjectT $object
     */
    #[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Clerk\Backend\Models\Components\ObjectT>')]
    public ObjectT $object;

    /**
     * String representing the identifier of the session.
     *
     *
     *
     * @var string $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;

    /**
     * $sessionIds
     *
     * @var array<string> $sessionIds
     */
    #[\JMS\Serializer\Annotation\SerializedName('session_ids')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $sessionIds;

    /**
     * $sessions
     *
     * @var array<\Clerk\Backend\Models\Components\Session> $sessions
     */
    #[\JMS\Serializer\Annotation\SerializedName('sessions')]
    #[\JMS\Serializer\Annotation\Type('array<Clerk\Backend\Models\Components\Session>')]
    public array $sessions;

    #[\JMS\Serializer\Annotation\SerializedName('sign_in_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $signInId;

    #[\JMS\Serializer\Annotation\SerializedName('sign_up_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $signUpId;

    /**
     * Last active session_id.
     *
     *
     *
     * @var string $lastActiveSessionId
     */
    #[\JMS\Serializer\Annotation\SerializedName('last_active_session_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $lastActiveSessionId;

    /**
     * Unix timestamp of last update.
     *
     *
     *
     * @var int $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $updatedAt;

    /**
     * Unix timestamp of creation.
     *
     *
     *
     * @var int $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;

    public function __construct()
    {
        $this->object = \Clerk\Backend\Models\Components\ObjectT::Client;
        $this->id = '';
        $this->sessionIds = [];
        $this->sessions = [];
        $this->signInId = '';
        $this->signUpId = '';
        $this->lastActiveSessionId = '';
        $this->updatedAt = 0;
        $this->createdAt = 0;
    }
}