<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Client
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     *
     *
     * @var ObjectT $object
     */
    #[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ObjectT')]
    public ObjectT $object;

    /**
     * String representing the identifier of the session.
     *
     *
     *
     * @var string $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * $sessionIds
     *
     * @var array<string> $sessionIds
     */
    #[\JMS\Serializer\Annotation\SerializedName('session_ids')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $sessionIds;

    /**
     * $sessions
     *
     * @var array<Session> $sessions
     */
    #[\JMS\Serializer\Annotation\SerializedName('sessions')]
    #[\JMS\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\Session>')]
    public array $sessions;

    /**
     *
     * @var string $signInId
     */
    #[\JMS\Serializer\Annotation\SerializedName('sign_in_id')]
    public string $signInId;

    /**
     *
     * @var string $signUpId
     */
    #[\JMS\Serializer\Annotation\SerializedName('sign_up_id')]
    public string $signUpId;

    /**
     * Last active session_id.
     *
     *
     *
     * @var string $lastActiveSessionId
     */
    #[\JMS\Serializer\Annotation\SerializedName('last_active_session_id')]
    public string $lastActiveSessionId;

    /**
     * Unix timestamp of last update.
     *
     *
     *
     * @var int $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     * Unix timestamp of creation.
     *
     *
     *
     * @var int $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * @param  ?ObjectT  $object
     * @param  ?string  $id
     * @param  ?array<string>  $sessionIds
     * @param  ?array<Session>  $sessions
     * @param  ?string  $signInId
     * @param  ?string  $signUpId
     * @param  ?string  $lastActiveSessionId
     * @param  ?int  $updatedAt
     * @param  ?int  $createdAt
     */
    public function __construct(?ObjectT $object = null, ?string $id = null, ?array $sessionIds = null, ?array $sessions = null, ?string $signInId = null, ?string $signUpId = null, ?string $lastActiveSessionId = null, ?int $updatedAt = null, ?int $createdAt = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->sessionIds = $sessionIds;
        $this->sessions = $sessions;
        $this->signInId = $signInId;
        $this->signUpId = $signUpId;
        $this->lastActiveSessionId = $lastActiveSessionId;
        $this->updatedAt = $updatedAt;
        $this->createdAt = $createdAt;
    }
}