<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** DeletedObject - Deleted Object */
class DeletedObject
{
    /**
     *
     * @var string $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    public string $object;

    /**
     *
     * @var bool $deleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deleted')]
    public bool $deleted;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $slug = null;

    /**
     * @param  string  $object
     * @param  bool  $deleted
     * @param  ?string  $id
     * @param  ?string  $slug
     */
    public function __construct(string $object, bool $deleted, ?string $id = null, ?string $slug = null)
    {
        $this->object = $object;
        $this->deleted = $deleted;
        $this->id = $id;
        $this->slug = $slug;
    }
}