<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class EmailAddress
{
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;

    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     *
     *
     * @var \Clerk\Backend\Models\Components\EmailAddressObject $object
     */
    #[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Clerk\Backend\Models\Components\EmailAddressObject>')]
    public EmailAddressObject $object;

    #[\JMS\Serializer\Annotation\SerializedName('email_address')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $emailAddress;

    #[\JMS\Serializer\Annotation\SerializedName('reserved')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $reserved;

    #[\JMS\Serializer\Annotation\SerializedName('verification')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $verification;

    /**
     * $linkedTo
     *
     * @var array<\Clerk\Backend\Models\Components\IdentificationLink> $linkedTo
     */
    #[\JMS\Serializer\Annotation\SerializedName('linked_to')]
    #[\JMS\Serializer\Annotation\Type('array<Clerk\Backend\Models\Components\IdentificationLink>')]
    public array $linkedTo;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var int $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var int $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $updatedAt;

    public function __construct()
    {
        $this->id = null;
        $this->object = \Clerk\Backend\Models\Components\EmailAddressObject::EmailAddress;
        $this->emailAddress = '';
        $this->reserved = false;
        $this->verification = null;
        $this->linkedTo = [];
        $this->createdAt = 0;
        $this->updatedAt = 0;
    }
}