<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** Mode of enrollment for the domain */
enum EnrollmentMode: string
{
    case ManualInvitation = 'manual_invitation';
    case AutomaticInvitation = 'automatic_invitation';
    case AutomaticSuggestion = 'automatic_suggestion';
}
