<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** InstanceRestrictions - Success */
class InstanceRestrictions
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     * @var ?InstanceRestrictionsObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\InstanceRestrictionsObject|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InstanceRestrictionsObject $object = null;

    /**
     *
     * @var ?bool $allowlist
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowlist')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowlist = null;

    /**
     *
     * @var ?bool $blocklist
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('blocklist')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $blocklist = null;

    /**
     *
     * @var ?bool $blockEmailSubaddresses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('block_email_subaddresses')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $blockEmailSubaddresses = null;

    /**
     *
     * @var ?bool $ignoreDotsForGmailAddresses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ignore_dots_for_gmail_addresses')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $ignoreDotsForGmailAddresses = null;

    /**
     * @param  ?InstanceRestrictionsObject  $object
     * @param  ?bool  $allowlist
     * @param  ?bool  $blocklist
     * @param  ?bool  $blockEmailSubaddresses
     * @param  ?bool  $ignoreDotsForGmailAddresses
     */
    public function __construct(?InstanceRestrictionsObject $object = null, ?bool $allowlist = null, ?bool $blocklist = null, ?bool $blockEmailSubaddresses = null, ?bool $ignoreDotsForGmailAddresses = null)
    {
        $this->object = $object;
        $this->allowlist = $allowlist;
        $this->blocklist = $blocklist;
        $this->blockEmailSubaddresses = $blockEmailSubaddresses;
        $this->ignoreDotsForGmailAddresses = $ignoreDotsForGmailAddresses;
    }
}