<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class LatestActivity
{
    /**
     *
     * @var string $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    public string $object;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var ?string $deviceType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('device_type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $deviceType = null;

    /**
     *
     * @var ?bool $isMobile
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_mobile')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isMobile = null;

    /**
     *
     * @var ?string $browserName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('browser_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $browserName = null;

    /**
     *
     * @var ?string $browserVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('browser_version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $browserVersion = null;

    /**
     *
     * @var ?string $ipAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ip_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ipAddress = null;

    /**
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     *
     * @var ?string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $country = null;

    /**
     * @param  string  $object
     * @param  string  $id
     * @param  ?string  $deviceType
     * @param  ?bool  $isMobile
     * @param  ?string  $browserName
     * @param  ?string  $browserVersion
     * @param  ?string  $ipAddress
     * @param  ?string  $city
     * @param  ?string  $country
     */
    public function __construct(string $object, string $id, ?string $deviceType = null, ?bool $isMobile = null, ?string $browserName = null, ?string $browserVersion = null, ?string $ipAddress = null, ?string $city = null, ?string $country = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->deviceType = $deviceType;
        $this->isMobile = $isMobile;
        $this->browserName = $browserName;
        $this->browserVersion = $browserVersion;
        $this->ipAddress = $ipAddress;
        $this->city = $city;
        $this->country = $country;
    }
}