<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Oauth
{
    /**
     *
     * @var OauthVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OauthVerificationStatus')]
    public OauthVerificationStatus $status;

    /**
     *
     * @var OauthVerificationStrategy $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OauthVerificationStrategy')]
    public OauthVerificationStrategy $strategy;

    /**
     *
     * @var ?string $externalVerificationRedirectUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_verification_redirect_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalVerificationRedirectUrl = null;

    /**
     *
     * @var ?ErrorClerkError $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ErrorClerkError')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ErrorClerkError $error = null;

    /**
     *
     * @var int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    public int $expireAt;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $attempts = null;

    /**
     * @param  OauthVerificationStatus  $status
     * @param  OauthVerificationStrategy  $strategy
     * @param  int  $expireAt
     * @param  ?string  $externalVerificationRedirectUrl
     * @param  ?ErrorClerkError  $error
     * @param  ?int  $attempts
     */
    public function __construct(OauthVerificationStatus $status, OauthVerificationStrategy $strategy, int $expireAt, ?string $externalVerificationRedirectUrl = null, ?ErrorClerkError $error = null, ?int $attempts = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->expireAt = $expireAt;
        $this->externalVerificationRedirectUrl = $externalVerificationRedirectUrl;
        $this->error = $error;
        $this->attempts = $attempts;
    }
}