<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** OrganizationMemberships - A list of organization memberships */
class OrganizationMemberships
{
    /**
     * $data
     *
     * @var array<OrganizationMembership> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\OrganizationMembership>')]
    public array $data;

    /**
     * Total number of organization memberships
     *
     *
     *
     * @var int $totalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_count')]
    public int $totalCount;

    /**
     * @param  array<OrganizationMembership>  $data
     * @param  int  $totalCount
     */
    public function __construct(array $data, int $totalCount)
    {
        $this->data = $data;
        $this->totalCount = $totalCount;
    }
}