<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** OrganizationDomain - An organization domain */
class OrganizationDomain
{
    /**
     * Unique identifier for the organization domain
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * String representing the object's type. Objects of the same type share the same value. Always `organization_domain`
     *
     *
     *
     * @var ?OrganizationDomainObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OrganizationDomainObject|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrganizationDomainObject $object = null;

    /**
     * Unique identifier for the organization
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organizationId = null;

    /**
     * Name of the organization domain
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Mode of enrollment for the domain
     *
     * @var ?EnrollmentMode $enrollmentMode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enrollment_mode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\EnrollmentMode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?EnrollmentMode $enrollmentMode = null;

    /**
     * Total number of pending invitations associated with this domain
     *
     * @var ?int $totalPendingInvitations
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_pending_invitations')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $totalPendingInvitations = null;

    /**
     * Total number of pending suggestions associated with this domain
     *
     * @var ?int $totalPendingSuggestions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_pending_suggestions')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $totalPendingSuggestions = null;

    /**
     * Unix timestamp when the domain was created
     *
     * @var ?int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $createdAt = null;

    /**
     * Unix timestamp of the last update to the domain
     *
     * @var ?int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $updatedAt = null;

    /**
     * Affiliation email address for the domain, if available.
     *
     * @var ?string $affiliationEmailAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('affiliation_email_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $affiliationEmailAddress = null;

    /**
     * Verification details for the domain
     *
     * @var ?OrganizationDomainVerification $verification
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verification')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OrganizationDomainVerification|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrganizationDomainVerification $verification = null;

    /**
     * @param  ?string  $id
     * @param  ?OrganizationDomainObject  $object
     * @param  ?string  $organizationId
     * @param  ?string  $name
     * @param  ?EnrollmentMode  $enrollmentMode
     * @param  ?int  $totalPendingInvitations
     * @param  ?int  $totalPendingSuggestions
     * @param  ?int  $createdAt
     * @param  ?int  $updatedAt
     * @param  ?string  $affiliationEmailAddress
     * @param  ?OrganizationDomainVerification  $verification
     */
    public function __construct(?string $id = null, ?OrganizationDomainObject $object = null, ?string $organizationId = null, ?string $name = null, ?EnrollmentMode $enrollmentMode = null, ?int $totalPendingInvitations = null, ?int $totalPendingSuggestions = null, ?int $createdAt = null, ?int $updatedAt = null, ?string $affiliationEmailAddress = null, ?OrganizationDomainVerification $verification = null)
    {
        $this->id = $id;
        $this->object = $object;
        $this->organizationId = $organizationId;
        $this->name = $name;
        $this->enrollmentMode = $enrollmentMode;
        $this->totalPendingInvitations = $totalPendingInvitations;
        $this->totalPendingSuggestions = $totalPendingSuggestions;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->affiliationEmailAddress = $affiliationEmailAddress;
        $this->verification = $verification;
    }
}