<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Organization
{
    /**
     *
     * @var OrganizationObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OrganizationObject')]
    public OrganizationObject $object;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    public string $slug;

    /**
     *
     * @var ?int $membersCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('members_count')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $membersCount = null;

    /**
     *
     * @var int $maxAllowedMemberships
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('max_allowed_memberships')]
    public int $maxAllowedMemberships;

    /**
     *
     * @var ?bool $adminDeleteEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('admin_delete_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $adminDeleteEnabled = null;

    /**
     *
     * @var OrganizationPublicMetadata $publicMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OrganizationPublicMetadata')]
    public OrganizationPublicMetadata $publicMetadata;

    /**
     *
     * @var OrganizationPrivateMetadata $privateMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('private_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OrganizationPrivateMetadata')]
    public OrganizationPrivateMetadata $privateMetadata;

    /**
     *
     * @var ?string $createdBy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_by')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $createdBy = null;

    /**
     * Unix timestamp of creation.
     *
     *
     *
     * @var int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Unix timestamp of last update.
     *
     *
     *
     * @var int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     * @param  OrganizationObject  $object
     * @param  string  $id
     * @param  string  $name
     * @param  string  $slug
     * @param  int  $maxAllowedMemberships
     * @param  OrganizationPublicMetadata  $publicMetadata
     * @param  OrganizationPrivateMetadata  $privateMetadata
     * @param  int  $createdAt
     * @param  int  $updatedAt
     * @param  ?bool  $adminDeleteEnabled
     * @param  ?string  $createdBy
     * @param  ?int  $membersCount
     */
    public function __construct(OrganizationObject $object, string $id, string $name, string $slug, int $maxAllowedMemberships, OrganizationPublicMetadata $publicMetadata, OrganizationPrivateMetadata $privateMetadata, int $createdAt, int $updatedAt, ?bool $adminDeleteEnabled = null, ?string $createdBy = null, ?int $membersCount = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->name = $name;
        $this->slug = $slug;
        $this->maxAllowedMemberships = $maxAllowedMemberships;
        $this->publicMetadata = $publicMetadata;
        $this->privateMetadata = $privateMetadata;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->adminDeleteEnabled = $adminDeleteEnabled;
        $this->createdBy = $createdBy;
        $this->membersCount = $membersCount;
    }
}