<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class OrganizationMembershipOrganization
{
    /**
     *
     * @var OrganizationMembershipOrganizationObject $object
     */
    #[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OrganizationMembershipOrganizationObject')]
    public OrganizationMembershipOrganizationObject $object;

    /**
     *
     * @var string $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $name
     */
    #[\JMS\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $slug
     */
    #[\JMS\Serializer\Annotation\SerializedName('slug')]
    public string $slug;

    /**
     *
     * @var ?int $membersCount
     */
    #[\JMS\Serializer\Annotation\SerializedName('members_count')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $membersCount = null;

    /**
     *
     * @var int $maxAllowedMemberships
     */
    #[\JMS\Serializer\Annotation\SerializedName('max_allowed_memberships')]
    public int $maxAllowedMemberships;

    /**
     *
     * @var ?bool $adminDeleteEnabled
     */
    #[\JMS\Serializer\Annotation\SerializedName('admin_delete_enabled')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $adminDeleteEnabled = null;

    /**
     *
     * @var OrganizationMembershipOrganizationPublicMetadata $publicMetadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('public_metadata')]
    #[\JMS\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OrganizationMembershipOrganizationPublicMetadata')]
    public OrganizationMembershipOrganizationPublicMetadata $publicMetadata;

    /**
     *
     * @var OrganizationMembershipOrganizationPrivateMetadata $privateMetadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('private_metadata')]
    #[\JMS\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OrganizationMembershipOrganizationPrivateMetadata')]
    public OrganizationMembershipOrganizationPrivateMetadata $privateMetadata;

    /**
     *
     * @var ?string $createdBy
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_by')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $createdBy = null;

    /**
     * Unix timestamp of creation.
     *
     *
     *
     * @var int $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Unix timestamp of last update.
     *
     *
     *
     * @var int $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     * @param  ?OrganizationMembershipOrganizationObject  $object
     * @param  ?string  $id
     * @param  ?string  $name
     * @param  ?string  $slug
     * @param  ?int  $maxAllowedMemberships
     * @param  ?OrganizationMembershipOrganizationPublicMetadata  $publicMetadata
     * @param  ?OrganizationMembershipOrganizationPrivateMetadata  $privateMetadata
     * @param  ?int  $createdAt
     * @param  ?int  $updatedAt
     * @param  ?int  $membersCount
     * @param  ?bool  $adminDeleteEnabled
     * @param  ?string  $createdBy
     */
    public function __construct(?OrganizationMembershipOrganizationObject $object = null, ?string $id = null, ?string $name = null, ?string $slug = null, ?int $maxAllowedMemberships = null, ?OrganizationMembershipOrganizationPublicMetadata $publicMetadata = null, ?OrganizationMembershipOrganizationPrivateMetadata $privateMetadata = null, ?int $createdAt = null, ?int $updatedAt = null, ?int $membersCount = null, ?bool $adminDeleteEnabled = null, ?string $createdBy = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->name = $name;
        $this->slug = $slug;
        $this->maxAllowedMemberships = $maxAllowedMemberships;
        $this->publicMetadata = $publicMetadata;
        $this->privateMetadata = $privateMetadata;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->membersCount = $membersCount;
        $this->adminDeleteEnabled = $adminDeleteEnabled;
        $this->createdBy = $createdBy;
    }
}