<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Passkey
{
    /**
     *
     * @var PasskeyVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\PasskeyVerificationStatus')]
    public PasskeyVerificationStatus $status;

    /**
     *
     * @var PasskeyVerificationStrategy $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\PasskeyVerificationStrategy')]
    public PasskeyVerificationStrategy $strategy;

    /**
     *
     * @var ?VerificationNonce $nonce
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nonce')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationNonce|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerificationNonce $nonce = null;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $attempts = null;

    /**
     *
     * @var ?int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $expireAt = null;

    /**
     * @param  PasskeyVerificationStatus  $status
     * @param  PasskeyVerificationStrategy  $strategy
     * @param  ?VerificationNonce  $nonce
     * @param  ?int  $attempts
     * @param  ?int  $expireAt
     */
    public function __construct(PasskeyVerificationStatus $status, PasskeyVerificationStrategy $strategy, ?VerificationNonce $nonce = null, ?int $attempts = null, ?int $expireAt = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->nonce = $nonce;
        $this->attempts = $attempts;
        $this->expireAt = $expireAt;
    }
}