<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class PhoneNumber
{
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;

    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     *
     *
     * @var \Clerk\Backend\Models\Components\PhoneNumberObject $object
     */
    #[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Clerk\Backend\Models\Components\PhoneNumberObject>')]
    public PhoneNumberObject $object;

    #[\JMS\Serializer\Annotation\SerializedName('phone_number')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $phoneNumber;

    #[\JMS\Serializer\Annotation\SerializedName('reserved_for_second_factor')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $reservedForSecondFactor = null;

    #[\JMS\Serializer\Annotation\SerializedName('default_second_factor')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $defaultSecondFactor = null;

    #[\JMS\Serializer\Annotation\SerializedName('reserved')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $reserved;

    #[\JMS\Serializer\Annotation\SerializedName('verification')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $verification;

    /**
     * $linkedTo
     *
     * @var array<\Clerk\Backend\Models\Components\IdentificationLink> $linkedTo
     */
    #[\JMS\Serializer\Annotation\SerializedName('linked_to')]
    #[\JMS\Serializer\Annotation\Type('array<Clerk\Backend\Models\Components\IdentificationLink>')]
    public array $linkedTo;

    /**
     * $backupCodes
     *
     * @var ?array<string> $backupCodes
     */
    #[\JMS\Serializer\Annotation\SerializedName('backup_codes')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $backupCodes = null;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var int $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var int $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $updatedAt;

    public function __construct()
    {
        $this->id = null;
        $this->object = \Clerk\Backend\Models\Components\PhoneNumberObject::PhoneNumber;
        $this->phoneNumber = '';
        $this->reservedForSecondFactor = null;
        $this->defaultSecondFactor = null;
        $this->reserved = false;
        $this->verification = null;
        $this->linkedTo = [];
        $this->backupCodes = null;
        $this->createdAt = 0;
        $this->updatedAt = 0;
    }
}