<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class ProxyCheck
{
    #[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Clerk\Backend\Models\Components\ProxyCheckObject>')]
    public ProxyCheckObject $object;

    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;

    #[\JMS\Serializer\Annotation\SerializedName('domain_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $domainId;

    #[\JMS\Serializer\Annotation\SerializedName('last_run_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $lastRunAt;

    #[\JMS\Serializer\Annotation\SerializedName('proxy_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $proxyUrl;

    #[\JMS\Serializer\Annotation\SerializedName('successful')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $successful;

    #[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;

    #[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $updatedAt;

    public function __construct()
    {
        $this->object = \Clerk\Backend\Models\Components\ProxyCheckObject::ProxyCheck;
        $this->id = '';
        $this->domainId = '';
        $this->lastRunAt = 0;
        $this->proxyUrl = '';
        $this->successful = false;
        $this->createdAt = 0;
        $this->updatedAt = 0;
    }
}