<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class PublicUserData
{
    /**
     *
     * @var ?string $userId
     */
    #[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $userId = null;

    /**
     *
     * @var ?string $firstName
     */
    #[\JMS\Serializer\Annotation\SerializedName('first_name')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\JMS\Serializer\Annotation\SerializedName('last_name')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lastName = null;

    /**
     *
     * @var ?string $profileImageUrl
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\JMS\Serializer\Annotation\SerializedName('profile_image_url')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $profileImageUrl = null;

    /**
     *
     * @var ?string $imageUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('image_url')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $imageUrl = null;

    /**
     *
     * @var ?bool $hasImage
     */
    #[\JMS\Serializer\Annotation\SerializedName('has_image')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $hasImage = null;

    /**
     *
     * @var ?string $identifier
     */
    #[\JMS\Serializer\Annotation\SerializedName('identifier')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $identifier = null;

    /**
     * @param  ?string  $userId
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $profileImageUrl
     * @param  ?string  $imageUrl
     * @param  ?bool  $hasImage
     * @param  ?string  $identifier
     */
    public function __construct(?string $userId = null, ?string $firstName = null, ?string $lastName = null, ?string $profileImageUrl = null, ?string $imageUrl = null, ?bool $hasImage = null, ?string $identifier = null)
    {
        $this->userId = $userId;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->profileImageUrl = $profileImageUrl;
        $this->imageUrl = $imageUrl;
        $this->hasImage = $hasImage;
        $this->identifier = $identifier;
    }
}