<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class SAMLAccount
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     *
     *
     * @var SAMLAccountObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SAMLAccountObject')]
    public SAMLAccountObject $object;

    /**
     *
     * @var string $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    public string $provider;

    /**
     *
     * @var bool $active
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active')]
    public bool $active;

    /**
     *
     * @var string $emailAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email_address')]
    public string $emailAddress;

    /**
     * $publicMetadata
     *
     * @var ?array<string, mixed> $publicMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $publicMetadata = null;

    /**
     *
     * @var Saml|Ticket|null $verification
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verification')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Saml|\Clerk\Backend\Models\Components\Ticket')]
    public Saml|Ticket|null $verification;

    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     *
     * @var ?string $providerUserId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider_user_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $providerUserId = null;

    /**
     *
     * @var ?SAMLConnectionSAMLConnection $samlConnection
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('saml_connection')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SAMLConnectionSAMLConnection')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SAMLConnectionSAMLConnection $samlConnection = null;

    /**
     * @param  string  $id
     * @param  SAMLAccountObject  $object
     * @param  string  $provider
     * @param  bool  $active
     * @param  string  $emailAddress
     * @param  ?array<string, mixed>  $publicMetadata
     * @param  Saml|Ticket|null  $verification
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $providerUserId
     * @param  ?SAMLConnectionSAMLConnection  $samlConnection
     */
    public function __construct(string $id, SAMLAccountObject $object, string $provider, bool $active, string $emailAddress, ?array $publicMetadata = null, Saml|Ticket|null $verification = null, ?string $firstName = null, ?string $lastName = null, ?string $providerUserId = null, ?SAMLConnectionSAMLConnection $samlConnection = null)
    {
        $this->id = $id;
        $this->object = $object;
        $this->provider = $provider;
        $this->active = $active;
        $this->emailAddress = $emailAddress;
        $this->publicMetadata = $publicMetadata;
        $this->verification = $verification;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->providerUserId = $providerUserId;
        $this->samlConnection = $samlConnection;
    }
}