<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


enum Status: string
{
    case Active = 'active';
    case Revoked = 'revoked';
    case Ended = 'ended';
    case Expired = 'expired';
    case Removed = 'removed';
    case Abandoned = 'abandoned';
    case Replaced = 'replaced';
}
