<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class SvixURL
{
    /**
     *
     * @var string $svixUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('svix_url')]
    public string $svixUrl;

    /**
     * @param  ?string  $svixUrl
     */
    public function __construct(?string $svixUrl = null)
    {
        $this->svixUrl = $svixUrl;
    }
}