<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Template
{
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;

    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     *
     *
     * @var ?\Clerk\Backend\Models\Components\TemplateObject $object
     */
    #[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Clerk\Backend\Models\Components\TemplateObject>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TemplateObject $object = null;

    /**
     * the id of the instance the template belongs to
     *
     * @var ?string $instanceId
     */
    #[\JMS\Serializer\Annotation\SerializedName('instance_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $instanceId = null;

    /**
     * whether this is a system (default) or user overridden) template
     *
     * @var ?string $resourceType
     */
    #[\JMS\Serializer\Annotation\SerializedName('resource_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $resourceType = null;

    /**
     * whether this is an email or SMS template
     *
     * @var ?string $templateType
     */
    #[\JMS\Serializer\Annotation\SerializedName('template_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $templateType = null;

    /**
     * user-friendly name of the template
     *
     * @var ?string $name
     */
    #[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;

    /**
     * machine-friendly name of the template
     *
     * @var ?string $slug
     */
    #[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $slug = null;

    /**
     * position with the listing of templates
     *
     * @var ?int $position
     */
    #[\JMS\Serializer\Annotation\SerializedName('position')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $position = null;

    /**
     * whether this template can be reverted to the corresponding system default
     *
     * @var ?bool $canRevert
     */
    #[\JMS\Serializer\Annotation\SerializedName('can_revert')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $canRevert = null;

    /**
     * whether this template can be deleted
     *
     * @var ?bool $canDelete
     */
    #[\JMS\Serializer\Annotation\SerializedName('can_delete')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $canDelete = null;

    /**
     * whether this template can be enabled or disabled, true only for notification SMS templates
     *
     * @var ?bool $canToggle
     */
    #[\JMS\Serializer\Annotation\SerializedName('can_toggle')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $canToggle = null;

    /**
     * email subject
     *
     * @var ?string $subject
     */
    #[\JMS\Serializer\Annotation\SerializedName('subject')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $subject = null;

    /**
     * the editor markup used to generate the body of the template
     *
     * @var ?string $markup
     */
    #[\JMS\Serializer\Annotation\SerializedName('markup')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $markup = null;

    /**
     * the template body before variable interpolation
     *
     * @var ?string $body
     */
    #[\JMS\Serializer\Annotation\SerializedName('body')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $body = null;

    /**
     * list of variables that are available for use in the template body
     *
     * @var ?array<string> $availableVariables
     */
    #[\JMS\Serializer\Annotation\SerializedName('available_variables')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $availableVariables = null;

    /**
     * list of variables that must be contained in the template body
     *
     * @var ?array<string> $requiredVariables
     */
    #[\JMS\Serializer\Annotation\SerializedName('required_variables')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $requiredVariables = null;

    #[\JMS\Serializer\Annotation\SerializedName('from_email_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fromEmailName = null;

    #[\JMS\Serializer\Annotation\SerializedName('reply_to_email_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $replyToEmailName = null;

    #[\JMS\Serializer\Annotation\SerializedName('delivered_by_clerk')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $deliveredByClerk = null;

    #[\JMS\Serializer\Annotation\SerializedName('enabled')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $enabled = null;

    /**
     * Unix timestamp of last update.
     *
     *
     *
     * @var ?int $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $updatedAt = null;

    /**
     * Unix timestamp of creation.
     *
     *
     *
     * @var ?int $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $createdAt = null;

    public function __construct()
    {
        $this->id = null;
        $this->object = null;
        $this->instanceId = null;
        $this->resourceType = null;
        $this->templateType = null;
        $this->name = null;
        $this->slug = null;
        $this->position = null;
        $this->canRevert = null;
        $this->canDelete = null;
        $this->canToggle = null;
        $this->subject = null;
        $this->markup = null;
        $this->body = null;
        $this->availableVariables = null;
        $this->requiredVariables = null;
        $this->fromEmailName = null;
        $this->replyToEmailName = null;
        $this->deliveredByClerk = null;
        $this->enabled = null;
        $this->updatedAt = null;
        $this->createdAt = null;
    }
}