<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class TestingToken
{
    /**
     *
     * @var TestingTokenObject $object
     */
    #[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\TestingTokenObject')]
    public TestingTokenObject $object;

    /**
     * The actual token. This value is meant to be passed in the `__clerk_testing_token` query parameter with requests to the Frontend API.
     *
     * @var string $token
     */
    #[\JMS\Serializer\Annotation\SerializedName('token')]
    public string $token;

    /**
     * Unix timestamp of the token's expiration time.
     *
     *
     *
     * @var int $expiresAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('expires_at')]
    public int $expiresAt;

    /**
     * @param  ?TestingTokenObject  $object
     * @param  ?string  $token
     * @param  ?int  $expiresAt
     */
    public function __construct(?TestingTokenObject $object = null, ?string $token = null, ?int $expiresAt = null)
    {
        $this->object = $object;
        $this->token = $token;
        $this->expiresAt = $expiresAt;
    }
}