<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


enum VerificationStatus: string
{
    case Unverified = 'unverified';
    case Verified = 'verified';
    case Failed = 'failed';
    case Expired = 'expired';
}
