<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Web3Wallet
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     *
     *
     * @var Web3WalletObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Web3WalletObject')]
    public Web3WalletObject $object;

    /**
     *
     * @var string $web3Wallet
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('web3_wallet')]
    public string $web3Wallet;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var Web3Signature|Web3WalletVerificationAdmin|null $verification
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verification')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Web3Signature|\Clerk\Backend\Models\Components\Web3WalletVerificationAdmin')]
    public Web3Signature|Web3WalletVerificationAdmin|null $verification;

    /**
     * @param  Web3WalletObject  $object
     * @param  string  $web3Wallet
     * @param  int  $createdAt
     * @param  int  $updatedAt
     * @param  ?string  $id
     * @param  Web3Signature|Web3WalletVerificationAdmin|null  $verification
     */
    public function __construct(Web3WalletObject $object, string $web3Wallet, int $createdAt, int $updatedAt, ?string $id = null, Web3Signature|Web3WalletVerificationAdmin|null $verification = null)
    {
        $this->object = $object;
        $this->web3Wallet = $web3Wallet;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->id = $id;
        $this->verification = $verification;
    }
}